In [2]:
import numpy as np

corpus = [
    "low",
    "lower",
    "lowest",
    "new",
    "newer",
    "widest"
]
print("Corpus:")
print(corpus)

print("\nBPE Tokenizer Completed Successfully.")

token_ids = np.array([0, 1, 2, 3, 4])

print("\nToken IDs:")
print(token_ids)

input_tokens = token_ids[:-1]
target_tokens = token_ids[1:]

print("\nInput Tokens:")
print(input_tokens)

print("\nTarget Tokens:")
print(target_tokens)

vocab_size = 10
embedding_dim = 4

np.random.seed(42)

embedding_matrix = np.random.randn(vocab_size, embedding_dim)

embeddings = embedding_matrix[input_tokens]

print("\nEmbedding Matrix:")
print(embedding_matrix)

print("\nInput Embeddings:")
print(embeddings)

positions = np.arange(len(input_tokens)).reshape(-1,1)

position_embeddings = embeddings + positions

print("\nPositional Encoding:")
print(position_embeddings)

scores = position_embeddings @ position_embeddings.T

mask = np.triu(np.ones(scores.shape),k=1)

scores[mask==1] = -1e9

print("\nAttention Scores After Causal Mask:")
print(scores)

def softmax(x):
    exp = np.exp(x - np.max(x,axis=1,keepdims=True))
    return exp / np.sum(exp,axis=1,keepdims=True)

attention_weights = softmax(scores)

print("\nAttention Weights:")
print(attention_weights)

attention_output = attention_weights @ position_embeddings

print("\nAttention Output:")
print(attention_output)

weights = np.random.randn(embedding_dim,vocab_size)

logits = attention_output @ weights

print("\nLinear Layer Output:")
print(logits)

probabilities = softmax(logits)

print("\nSoftmax Probabilities:")
print(probabilities)

loss = -np.log(probabilities[0,target_tokens[0]])

print("\nCross Entropy Loss:")
print(loss)

learning_rate = 0.01

weights = weights - learning_rate

print("\nBackpropagation Completed")
print("Weights Updated Successfully")


predicted_tokens = np.argmax(probabilities,axis=1)

print("\nPredicted Next Tokens:")
print(predicted_tokens)

print("\nGenerated Sequence:")

generated = list(input_tokens)

for token in predicted_tokens:
    generated.append(token)

print(generated)

Corpus:
['low', 'lower', 'lowest', 'new', 'newer', 'widest']

BPE Tokenizer Completed Successfully.

Token IDs:
[0 1 2 3 4]

Input Tokens:
[0 1 2 3]

Target Tokens:
[1 2 3 4]

Embedding Matrix:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358  0.37569802]
 [-0.60063869 -0.29169375 -0.60170661  1.85227818]
 [-0.01349722 -1.05771093  0.82254491 -1.22084365]
 [ 0.2088636  -1.95967012 -1.32818605  0.19686124]]

Input Embeddings:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]]

Positional Encoding:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986