In [1]:
corpus = [
    "low",
    "lower",
    "lowest",
    "new",
    "newer",
    "widest"
]

print("Corpus:")
print(corpus)

Corpus:
['low', 'lower', 'lowest', 'new', 'newer', 'widest']


In [2]:
print("BPE Tokenizer Completed Successfully.")

BPE Tokenizer Completed Successfully.


In [3]:
import numpy as np

token_ids = np.array([0, 1, 2, 3, 4])

print("Token IDs:")
print(token_ids)


Token IDs:
[0 1 2 3 4]


In [4]:
input_tokens = token_ids[:-1]
target_tokens = token_ids[1:]

print("Input Tokens:")
print(input_tokens)

print("Target Tokens:")
print(target_tokens)

Input Tokens:
[0 1 2 3]
Target Tokens:
[1 2 3 4]


In [5]:
import numpy as np

vocab_size = 10
embedding_dim = 4

np.random.seed(42)

embedding_matrix = np.random.randn(vocab_size, embedding_dim)

embeddings = embedding_matrix[input_tokens]

print("Embeddings:")
print(embeddings)

Embeddings:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]]


In [6]:
positions = np.arange(len(input_tokens)).reshape(-1,1)

embeddings = embeddings + positions

print("Positional Encoding:")
print(embeddings)


Positional Encoding:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [ 0.76584663  0.76586304  2.57921282  1.76743473]
 [ 1.53052561  2.54256004  1.53658231  1.53427025]
 [ 3.24196227  1.08671976  1.27508217  2.43771247]]


In [7]:
scores = embeddings @ embeddings.T

mask = np.triu(np.ones(scores.shape), k=1)

scores[mask == 1] = -1e9

print("Causal Mask:")
print(scores)

Causal Mask:
[[ 3.00496235e+00 -1.00000000e+09 -1.00000000e+09 -1.00000000e+09]
 [ 4.63689778e+00  1.09492315e+01 -1.00000000e+09 -1.00000000e+09]
 [ 3.74065459e+00  9.79429594e+00  1.35221906e+01 -1.00000000e+09]
 [ 5.99863898e+00  1.09123303e+01  1.34243349e+01  1.92595558e+01]]


In [8]:
def softmax(x):
    exp = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp / np.sum(exp, axis=1, keepdims=True)

attention = softmax(scores)

output = attention @ embeddings

print("Attention Output:")
print(output)

Attention Output:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [ 0.76535936  0.76422611  2.57571577  1.76699223]
 [ 1.51251577  2.50069961  1.56101174  1.53974377]
 [ 3.236386    1.0908835   1.27615115  2.43492025]]


In [9]:
weights = np.random.randn(embedding_dim, vocab_size)

logits = output @ weights

print("Linear Layer Output:")
print(logits)


Linear Layer Output:
[[  0.56205819   2.3605906   -0.7349746    1.37409422  -4.34063957
    1.64388357  -0.02683682   0.76242024   0.49886007  -4.45557353]
 [  0.21723233   2.0763623   -3.51874273  -0.07936862  -2.87991756
    5.10635325  -1.02557225   2.62924206   1.60976383  -5.77748618]
 [  1.73583903   1.3745885   -3.64986323   1.61605231  -2.42344158
    4.62270197  -2.7737328    1.9317987    2.05392458  -4.29446708]
 [  3.01197148   3.64260147  -2.61180972   1.97602185  -9.00233216
    2.41825872  -2.28623655   3.63654151   2.15838363 -10.30451452]]


In [10]:
probabilities = softmax(logits)

print("Softmax Probabilities:")
print(probabilities)

Softmax Probabilities:
[[6.55898748e-02 3.96213713e-01 1.79284447e-02 1.47740501e-01
  4.87104582e-04 1.93494041e-01 3.63984548e-02 8.01406632e-02
  6.15729847e-02 4.34217209e-04]
 [6.38815504e-03 4.10001395e-02 1.52356889e-04 4.74857491e-03
  2.88602669e-04 8.48581748e-01 1.84345389e-03 7.12685571e-02
  2.57124935e-02 1.59185051e-05]
 [4.32050432e-02 3.01054645e-02 1.97949164e-04 3.83276095e-02
  6.74810496e-04 7.74966789e-01 4.75392453e-04 5.25579779e-02
  5.93850660e-02 1.03897663e-04]
 [1.64260192e-01 3.08611036e-01 5.93137231e-04 5.82941695e-02
  9.94916316e-07 9.07164720e-02 8.21390769e-04 3.06746519e-01
  6.99558175e-02 2.70555233e-07]]


In [11]:
loss = -np.log(probabilities[0][target_tokens[0]])

print("Cross Entropy Loss:")
print(loss)

Cross Entropy Loss:
0.925801532784411


In [12]:
print("Backpropagation Step")

learning_rate = 0.01

weights = weights - learning_rate

print("Weights Updated Successfully")

Backpropagation Step
Weights Updated Successfully


In [14]:
next_token = np.argmax(probabilities, axis=1)

print("Predicted Next Token:")
print(next_token)

Predicted Next Token:
[1 5 5 1]
